# Generated by Django 3.1.3 on 2021-04-06 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishingredient',
            name='status',
        ),
        migrations.AlterField(
            model_name='ordereddishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dishingredient'),
        ),
        migrations.CreateModel(
            name='DishIngredientStandardPortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_or_volume', models.FloatField()),
                ('dish_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dishingredient')),
            ],
        ),
    ]
