# Generated by Django 3.1.3 on 2021-04-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210406_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringestablishment',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
