# Generated by Django 3.1.3 on 2021-04-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cateringestablishment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishingredientstandardportion',
            name='is_liquid',
            field=models.BooleanField(default=False),
        ),
    ]
